document.write("<table>")
codename = navigator.appCodeName
document.write("<tr><td></td></tr>")
document.write("<tr><td></td></tr>")
document.write("<tr><td></td></tr>")
document.write("<tr><td></td></tr>")
document.write("<tr><td></td></tr>")
document.write("<tr><td></td></tr>")
document.write("<tr><td></td></tr>")
document.write("<tr><td></td></tr>")
document.write("<tr><td></td></tr>")
document.write("<tr><td></td></tr>")
document.write("</table>")